services:
  - type: web
    name: urbanav-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_API_TOKEN
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID_WEB
        sync: false
      - key: GOOGLE_CLIENT_ID_ANDROID
        sync: false
      - key: GOOGLE_CLIENT_ID_IOS
        sync: false
      - key: GOOGLE_CLIENT_ID_EXPO
        sync: false
      - key: CLIENT_URL
        value: https://adminurbanav.vercel.app
    healthCheckPath: /api/health
